### ISSUE TITLE
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)

### ISSUE THREAD

**Issue by ifargan873** [Asatelit/pwa-pos-terminal#14]
HI have error 
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)

**Comment by Asatelit** [comment]
It looks like your version of the Node environment is not compatible with node-sass v4.x. Try to switch to Node.js v12.22.1 with Node Version Manager (nvm) and install NPM packages using `yarn`.
